version: "3.9"

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 mytodo_project.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SECRET_KEY: "super-secret-key"
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "whynot"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "whynot"
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
